version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/applications/all-composites-temp
hooks:
  ApplicationStop:
    - location: aws/scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: aws/scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: aws/scripts/start_server.sh
      timeout: 300
      runas: ubuntu
