version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/applications/farm-mgmt
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
